### ISSUE TITLE
Monitoring Sky box

### ISSUE THREAD

**Issue by GreenTurtwig** [dalhundal/sky-remote-cli#1]
It would be nice to be able to see what channel is currently on and the play status (i.e. Playing, Paused), if this is possible. :-)

**Comment by dalhundal** [comment]
This is not possible - this module is is just one way communication with
the sky box, same way as a real world physical remote control. There's no
way to get feedback from the box. For what you're after, try my other
module which is based on a different protocol and a lot more complicated -
http://github.com/dalhundal/sky-plus-hd - it's also not finished so you
will have to dig around in the v1-dev branch

**Comment by GreenTurtwig** [comment]
Ahh, that makes sense. I'll me sure to check out the other module.
Thanks :-)
