### ISSUE TITLE
Getting Sky On/Off Status

### ISSUE THREAD

**Issue by lolouk44** [dalhundal/sky-remote-cli#3]
Not an issue per se, more a question.
Is there a way to extract some info from the sky box itself? For example whether the box is on or off?
Calling the power function will toggle the box on or off, and without knowing its status, it's quite difficult to know what action will really be carried out on the box.

Thanks
Laurent

**Comment by dalhundal** [comment]
This is not possible - this module is is just one way communication with
the sky box, same way as a real world physical remote control. There's no
way to get feedback from the box. For what you're after, try my other
module which is based on a different protocol and a lot more complicated -
http://github.com/dalhundal/sky-plus-hd - it's also not finished so you
will have to dig around in the v1-dev branch

**Comment by dalhundal** [comment]
Hey @lolouk44 

An update on this - if you want to get the on/off status of a **SKY Q** box, this is possible using my other module - http://github.com/dalhundal/sky-q
