### ISSUE TITLE
Work with Sky Q?

### ISSUE THREAD

**Issue by jonohunt** [dalhundal/sky-remote-cli#4]
Not an issue, but wondering if this *should* work with Sky Q?

I've tried it, but not managed to get it to work (via Home Assistant on a Raspberry Pi). Or is it just the NodeJS one that works with Sky Q?
(I'm wanting to use it with Home Assistant, and not even sure if that could run sky-remote (JavaScript).

**Comment by dalhundal** [comment]
Hi @jonohunt,

This module *should* work with Sky Q, and now *it does*. The underlying module has worked with Sky Q for a while, I hadn't updated this to do the same. Done just now in b758fcb2.

Update to the latest version for the changes I've just pushed out (v1.1.0)

https://www.npmjs.com/package/sky-remote-cli

When using, just add the `--sky_q` flag, eg;

`sky-remote-cli --sky_q 192.168.0.40 power`
