### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by lolouk44** [dalhundal/sky-remote-cli#6]
Trying to get back into this. I'm trying to install as per your instructions but it fails.
See attached npm log. Can you advise please?
[npm-debug.log](https://github.com/dalhundal/sky-remote-cli/files/1468969/npm-debug.log)

**Comment by dalhundal** [comment]
Could be missing / outdated compiler;

Which OS?

If Ubuntu, try `sudo apt-get install build-essential `

**Comment by lolouk44** [comment]
Thanks. Ubuntu 16. Build essential is already installed. Any other idea?

**Comment by dalhundal** [comment]
Does `npm install xml2json` give the same error?

**Comment by lolouk44** [comment]
Slightly different error, see log.
Thanks
[npm-debug.log](https://github.com/dalhundal/sky-remote-cli/files/1472388/npm-debug.log)

**Comment by dalhundal** [comment]
That's because you typed xnl2json instead of xml2json

**Comment by lolouk44** [comment]
oh :( Been a long day.

xml2json installs with warnings but does install...

**Comment by dalhundal** [comment]
Does `npm install node-expat` fail?

**Comment by lolouk44** [comment]
Will try tonight when I'm back home.
Quick question, does your script provide a status for the box, as in "On" or "Standby"? That's mainly what I'm after for my home automation...
Thanks for your support with this

**Comment by dalhundal** [comment]
No, this doesn't - in fact, you asked this before too https://github.com/dalhundal/sky-remote-cli/issues/3.

Is it a Sky Q box? If so, my other module https://github.com/dalhundal/sky-q will give you this info easily.

**Comment by lolouk44** [comment]
No it's a Sky+ HD box. 
and I just realised that for some reason my issue appears on your sky-remote-cli hub and not the sky-plus-hd as I intended.
I know I asked for the status before but it was for the sky-remote-cli script. I was hoping the sky-plus-hd script may be different as you can get other statuses.
Do you think possible to obtain the box's status?
I've even tried a completely different way with an energy meter, but the box uses the same amount of power whether on or off (around 15wh)

**Comment by dalhundal** [comment]
Oh, I didn't realise this was supposed to be for the sky-plus-hd repo either, even though it says so in those npm-debug.log files.

No, I didn't find a way to do it with Sky Plus boxes, and I no longer have one in order to figure it out.

If you've gone as extreme as using an energy meter, you could monitor the colour of the power led.... not ideal though.

**Comment by lolouk44** [comment]
ok thanks, Guess I'll give up on the idea. thanks though for your help
